using HotelManagementAPI.Data;
using Microsoft.EntityFrameworkCore;

        public class BookingRepository:IBookingRepository
        {
        public readonly ApplicationDbContext _context;
        public BookingRepository(ApplicationDbContext context){
            _context = context;
        }
        public async Task<IEnumerable<Booking>>GetAllAsync(){
            return await _context.Bookings
            .Include(b => b.Guest)
            .Include(b => b.Room)
            .ToListAsync();
        }
        public async Task<Booking> CreateAsync(Booking booking)
            {
            var room = await _context.Rooms.FindAsync(booking.RoomId);
            if (room == null)
                throw new Exception("Room not found");

            var totalDays = (booking.CheckOutDate - booking.CheckInDate).Days;
            booking.TotalPrice = totalDays * room.PricePerNight;

            // The Id is automatically generated by the database when adding the entity
            _context.Bookings.Add(booking);
            await _context.SaveChangesAsync();

            var savedBooking = await _context.Bookings
                .Include(b => b.Guest)
                .Include(b => b.Room)
                .FirstOrDefaultAsync(b => b.Id == booking.Id);

            return savedBooking!;
        }

        public async Task<Booking?> UpdateAsync(Booking updatedBooking)
        {
            var existing = await _context.Bookings.FindAsync(updatedBooking.Id);
            if (existing == null)
                return null;

            existing.GuestId = updatedBooking.GuestId;
            existing.RoomId = updatedBooking.RoomId;
            existing.CheckInDate = updatedBooking.CheckInDate;
            existing.CheckOutDate = updatedBooking.CheckOutDate;

            var room = await _context.Rooms.FindAsync(updatedBooking.RoomId);
            if (room == null)
                throw new Exception("Room not found");

            var totalDays = (updatedBooking.CheckOutDate - updatedBooking.CheckInDate).Days;
            existing.TotalPrice = totalDays * room.PricePerNight;

            await _context.SaveChangesAsync();

            return existing;
        }
        public async Task<List<Guid>> GetBookedRoomIdsBetweenDates(DateTime checkIn, DateTime checkOut)
{
    // fetch all RoomIds where booking overlaps with the given date range
    return await _context.Bookings
        .Where(b => b.CheckInDate < checkOut && b.CheckOutDate > checkIn)
        .Select(b => b.RoomId)
        .Distinct()
        .ToListAsync();
}

        public async Task<bool> DeleteAsync(Guid id)
    {
        var booking = await _context.Bookings.FindAsync(id);
        if (booking == null)
            return false;

        _context.Bookings.Remove(booking);
        await _context.SaveChangesAsync();
        return true;
    }



}